src/index.test.ts
src/index.ts

Fixes #14 
Now, the IContext is an object of arbitrary key value pairs. Extend this to implement the Unlease Context (https://www.unleash-hosted.com/docs/the-unleash-context)
and fixes #3 
We want to allow a consumer of the UnleashClient to be able to send the properties field, as mentioned in the Unlease Context. This allows them to support custom activation strategies. In this PR I flatten the properties into the url search params, so a properties object like
```
properties: {
property1: 'property1Value',
property2: 'property2Value'
}
```
would yield url search params `properties.property1=property1Value&properties.property2=property2Value`

feat: Add support for Unleash Context properties

---

src/index.ts
src/metrics.ts
src/storage-provider-inmemory.test.ts
src/storage-provider-inmemory.ts
src/storage-provider-local.ts

Use `global` instead of `window` and allow passing a `fetch` instance.
Example nodejs usage:
```typescript
import { UnleashClient } from 'unleash-proxy-client';
import fetch from 'node-fetch';
const store = new Map();
const inMemoryStorage: IStorageProvider = {
save: async (key: string, value: any) => {
store.set(key, value);
},
get: async (key: string) => store.get(key),
};
const unleash = new UnleashClient({
url: config.UNLEASH_PROXY_URL,
clientKey: config.UNLEASH_PROXY_SECRET,
appName: config.UNLEASH_APP_NAME,
storageProvider: inMemoryStorage,
fetch,
});
unleash.start();
```

Feat / nodejs support

---

README.md
src/index.test.ts
src/index.ts

Today a user of the SDK will need to provide the full context to update the Unleash Context being used. It would be useful if the SDK could provide a setContextField(name, value) method which will only replace the specified field on the context, and preserve the rest.
fixes: #35

feat: setContextField() to updated single field on context

---

README.md

This came out from a discussion initiated in the Unleash slack. For someone who's just starting with a DIY version of Unleash, the original doc might be misleading, as the client is async and the information might not be available immediately.
I've also changed the order of the steps slightly to follow the guideline that is mentioned a bit later in the text:
> PS! Please remember that you should always register your event listeners before your call unleash.start(). If you register them after you have started the SDK you risk loosing important events.

Suggest using event emitter at the top of Readme

---

src/index.ts

Problem:
Currently there is no way to wait on the resolution of the new flags for when the unleash context was updated.
Usually there is no problem as you fire `updateContext` and forget, but you can observe it as a problem when you have a side effect ( like redirecting the page ) and you need the new unleash variants / values before executing the side-effect. 
Currently there is no way to wait on the resolution of the flags after the context was updated.
This PR fixes it, it has been tested manually and all tests are passing.
This is backwards compatible as consumers can still fire and forget like before, but now can also wait for the updateContext to finish.
Depending on how you see this, can be a bug or a feature. Named it as a feat for the moment.
Thanks

feat: async capabilites for updating context

---

README.md
package-lock.json
src/index.test.ts
src/index.ts

After a meeting with customer that wanted the possibility to disable
refreshing, they only needed toggle status updated at startup.
This PR adds the possibility to not fetch via a new `disableRefresh` flag, or by setting refreshInterval to `0` the client will no longer perform refreshes.

task: Allow turning off proxy refresh

---

README.md
src/index.test.ts
src/index.ts
src/metrics.test.ts
src/metrics.ts

According to https://github.com/Unleash/unleash-proxy/pull/39 I'm providing possibility to specify proxy secret header name (client key) also from browser side :)

feat: additional possibility to customize header for clientKey

---

src/index.test.ts
src/index.ts

This PR adds the missing property `enabled` to the `IVariant` interface.
Closes #77
Let me know if something is missing ;)

fix: add missing property `enabled` to `IVariant` interface

---

README.md
package-lock.json
package.json
src/index.ts
src/storage-provider-local.test.ts
src/storage-provider-local.ts

[Breaking Change] v2
Removing built-in support for react-native (will become optional as custom storageProvider provided by developer itself)
* if will remove a lot of installed dependencies (for react-native it's huge...)
* it will reduce amount of packages that needs to be maintained (dependabot, renovate...)
* it's a suggestion to create own client for react-native if more custom things are needed 
* instead of `react-native-async-storage` which fallbacks to window.localStorage I just used window.localStorage
Kind regards
Dziczek!

BREAKING CHANGE: remove built-in support for react native async storage

---

README.md
src/index.test.ts
src/index.ts

Pass headers via a simple key value record.

add ability to pass custom http headers

---

package.json

Should make imports like these work as expected:
```html
<script src="https://cdn.jsdelivr.net/npm/unleash-proxy-client"></script>
<script src="https://unpkg.com/unleash-proxy-client"></script>
```

fix: add browser field to package.json for CDNs

---

package.json

Seems like it breaks the React proxy client build.

Revert "fix: add browser field to package.json for CDNs (#104)"

---

.github/workflows/release_changelog.yml

This tags alphas and betas as prerelease so our Latest version does not display beta's as latest versions

Add prerelease argument to create-release

---

README.md
package-lock.json
src/index.test.ts
src/index.ts

This now checks if response is not ok, if it is not, we emit an error object with a type and a statusCode.
I'm wondering if we should add more logic when we receive a 401 and just stop the poll; but that can be a different improvement.
fixes #108

enhancement: emit errors if response is not ok

---

src/index.test.ts
src/index.ts

It is unexpected for "uppdateContext" to remove
the automatically generated sessionId. This fix keeps the sessionId as long as it is not specified in the new context passed in to the "updateContext" method.
Closes #118

fix: merge sessionId instead of removing it

---

README.md
src/events-handler.ts
src/index.test.ts
src/index.ts

Make it possible to enable impression data for all isEnabled / getVariant calls. This PR also introduces a "impressionData" flag to the event itself, so the implementer can choose to discard events when we do not know whether impressionData is enabled for this toggle.
The reason we need this override in the proxy-sdk is that it simply does not know anything about disabled toggles (by design, to not leak information to the end-user about toggles). This makes it impossible to get impression data for disabled toggles, as they are not exposed to the frontend at all.
**Todo:**

feat: add overide to get all impression events

---

src/index.test.ts
src/index.ts

This PR fixes a bug in how impression data is reported when `impressionDataAll` is set to true: When a feature has `impressionData: false` but `impressionDataAll` is set to true, it will now report `impressionData: false` instead of `impressionData: undefined`.
This is a bug because we should report the state of impression data for a feature when we can. In the original feature PR discussion, it was agreed to make `impressionData` a `boolean | undefined` where it would be reported as a boolean if we knew the state and `undefined` otherwise.
It seems to have been an oversight in the tests.
It's explained more thoroughly in the [callback section of Jest's testing asynchronous code](https://jestjs.io/docs/asynchronous#callbacks), but in short:
If you don't have the try/catch and one of the …

fix: Include impression data status when not enabled

---

README.md
src/index.ts
src/storage-provider-inmemory.test.ts
src/storage-provider-inmemory.ts

fix: nodejs support by default

---

src/index.test.ts
src/index.ts

Can handle await on updateContext before start

fix: update context can be awaited before start

---

README.md

This PR adds content that was available at docs.getunleash.io to the readme. It also restructures the readme a little based on the incoming content.
Because we're moving to automating SDK docs on docs.getunleash.io and we don't want to lose any content. Some of the content on docs.getunleash.io was missing or more informative, so I've incorporated it as best as I can.

docs: update readme with content from docs.getunleash.io

---

README.md

This change clarifies what the `environment` config option does and
that it is not the unleash environment.

docs: clarify `environment`

---

src/index.test.ts
src/util.test.ts
src/util.ts

This PR does three things:
- Adds tests for undefined/null properties 
- Updates test titles
- Formats the test suites
The new tests were brought on by #146
I've added two (three) new tests.
1. `src/util.test.ts`: Verify that object properties set to `null` or `undefined` are excluded from query params
2. `src/index.test.ts`: Verify that setting a context field to `null` or `undefined` removes it from the context
Two of the tests in `src/util.test.ts` seems to have had copy-paste mistakes in their titles. Looking at them, I believe the "not" in their descriptions should be removed.
This repo has prettier listed in its deps, but the test files were pretty unformatted. My editor auto-formats on save, so this led to a lot of changes. However, I've isolated the formatting changes into …

fix: Update tests

---

README.md
src/index.test.ts
src/index.ts
src/metrics.test.ts
src/metrics.ts

This PR updates how custom headers work. Previously, any custom headers you added would only get added to feature get/post requests. Now we also add them to metrics requests. This is in line with what the documentation implies and what we think it's reasonable to expect. As such, I consider this a bug fix.
The most relevant changes are in the `src/metrics.ts`. In short, we perform the same kind of method here as in `src/index.ts` to enrich the standard headers with any custom headers that are provided.
We also take care to pass the custom headers from the client constructor to the metrics constructor.
The change comes with the following tests:
1. Verify that the custom headers are passed on from the client constructor to the metrics constructor
2. Verify that custom headers ...
- are sent …

fix: use custom headers for metrics requests too

---

src/events-handler.ts
src/index.test.ts
src/index.ts
src/metrics.test.ts
src/metrics.ts
src/test/index.html
src/util.test.ts
src/util.ts

Main capability:
* adding reporting of metrics for variants
Changes:
* introducing SENT event for easier testing and integration with other tools. Same event is present in node.js SDK
* added metrics unit test for counting variants
* added component tests for the whole SDK client for metrics reporting
* formatting code
Next steps:
* Proxy/Edge should accumulate client SDK metrics

feat: report metrics for variants

---

tsconfig.json

Paths to some source files are incorrect
https://sourcemaps.io/report/1698835631581_https%3A%2F%2Funpkg.com%2Funleash-proxy-client%403.0.0%2Fbuild%2Fmain.esm.js
Similar issue: https://github.com/ezolenko/rollup-plugin-typescript2/issues/407#issuecomment-1200016679
Closes #178

fix: sourcemap path

---

README.md
src/index.test.ts
src/index.ts
src/test/testdata.json

https://linear.app/unleash/issue/SR-161/proxy-sdk-add-feature-enabled-property-to-variant-response
Adds a new "feature_enabled" property to the variant response, similar to https://github.com/Unleash/unleash-client-python/pull/285

feat: add feature_enabled property to variant response

---

README.md
src/index.test.ts
src/index.ts

This PR adds a new event that fires when an error was recorded and the subsequent HTTP call is successful.
Our React Proxy SDK will set an error based on the error event fired from this SDK when the HTTP call fails. Without this event we have no way to effectively reset this error, because the only event that is fired consistently is the UPDATE event, which is only fired when the response is not 304. This does not cover the case when you intermittently lose connection and the next call succeeds with 304.
We keep track of the sdkState internally in the SDK. When the HTTP calls error we change the state of the SDK to be in an error state. If the internal SDK state is set to error, and the HTTP call is successful we will emit a RECOVERED event that will allow subscribers to clear out stale …

feat: fire event when error is present and http call succeeds

---

src/index.test.ts
src/index.ts

Our network firewall blocks the requests made, because the header [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) is sent with an empty value, which is considered a violation.
According to MDN's doc:
*So I removed it when empty to match the spec ;)

fix: don't send empty If-None-Match header

---

src/index.test.ts
src/index.ts

Solves https://github.com/Unleash/unleash-proxy-client-js/issues/194

fix: add curent time to context defined fields

---

src/index.test.ts
src/index.ts

In sdk for set GET request adds content type in header but not necessary  and common waf unit block this request, i change code and set content type header adds only in POST request.
[Closes #197 ]

fix: adds content type only on post method

---

src/index.test.ts
src/index.ts

Fixes a bug where the Ready event was not emitted when bootstrap is defined and bootstrap override is false
Closes #199

Fix: ready not emitted when bootstrap is set and bootrstrapOverride is false

---

src/index.ts

Prevents the SDK entering the error state when a request is aborted. An aborted request doesn't indicate that there's an error, only that a new request has superseded the previous one.
An example of the current behavior:
1. Application starts up <- starts in `initializing` state
3. Request for `flags A`
5. Context updated with `userId`
6. Request for `flags B`
7. Request for `flags A` cancelled <- transitions to `error` state
8. Request for `flags B` completed <- transitions to `healthy` state
Expected behavior:
1. Application starts up <- starts in `initializing` state
3. Request for `flags A`
5. Context updated with `userId`
6. Request for `flags B`
7. Request for `flags A` cancelled <- remains in `initializing` state
8. Request for `flags B` completed <- transitions to `healthy` state …

fix: don't enter error state when request is aborted

---

src/index.test.ts

Tests for https://github.com/Unleash/unleash-proxy-client-js/pull/207. Abort controller should not trigger errors.

test: aborted requests should not trigger error state

---

src/index.test.ts
src/index.ts

In an environment where AbortController is not available, there should be a way to use this SDK without errors.
Related to https://github.com/Unleash/unleash-client-nextjs/issues/76
Internally: [1-2470](https://linear.app/unleash/issue/1-2470/nextjs-sdk-76-warnings-in-serverless)

feat: allow for AbortController to be optional

---

README.md

`context` and `createAbortController` where not on the list.

docs: add missing options

---

src/index.ts

Push model for state changes is not enough when passing client to React SDK,
see https://github.com/Unleash/proxy-client-react/issues/168

feat: allow access to sdk state

---

src/index.test.ts
src/index.ts

When bootstrapping there is an edge case when:
- state of the `this.ready` promise cannot be resolved synchronously
- `readyEventEmitted` is not set until toggles are received from the server
and that made `isReady()` hard to implement.
Previously, the SDK wouldn’t be “ready” if it only bootstrapped, but the attempt to fetch flags failed. Now, we set the SDK to ready both when it’s bootstrapped and when you successfully fetch flags; whichever comes first. Otherwise, the existing functionality hasn’t changed. Essentially, what you’re doing here is adding a separate variable to track flag fetch status, making readyEventEmitted more accurately do what it says

fix: ready state when bootstrapping

---

src/index.ts

Fixing incompatible type for the use case not caught by TS because of "any" type on lastError

fix: error method return type

---

src/storage-provider-local.test.ts
src/storage-provider-local.ts

Allows to configure custom key for local storage provider
```
const unleash = new UnleashClient({
...
storageProvider: new LocalStorageProvider('unleash:repository:custom-key')
});
```
Closes: https://github.com/Unleash/unleash-proxy-client-js/issues/210

feat: configurable storage key

---

README.md
src/index.test.ts
src/index.ts

In order to manage contexts where the internal refresh mechanism does not correspond to technical needs or constraints (Service Workers for example), we propose to make the `updateToggles` and `sendMetrics` methods available as public as discussed in this [conversation](https://github.com/Unleash/unleash-proxy-client-js/issues/201#issuecomment-2273099747).
Closes second part of #201

feat: make updateToggles and sendMetrics available as public methods

---

package.json
src/index.test.ts
src/index.ts
yarn.lock

So, all of our schemas (even our type definitions) define sessionId to be a string, however, when user does not set one, we generate one automatically as a number, and never convert it back to a string. Don't really know how Typescript allowed this to pass. I guess since we only write the id to localstorage and don't really directly return the generated number, it threw its hands up in the air and gave up.

fix: make sessionId be a string when set automatically

---

README.md

Updated the Readme to favour Edge and the front-end API over Proxy as much as possible.
I know the package is called `proxy-client` so there might be a larger discussion about renaming it but it's working great as it is.

Brought the Readme to modern times

---

package.json
src/index.test.ts
src/index.ts
src/metrics.test.ts
src/metrics.ts

This PR adds client identification headers to the feature and metrics calls that the client makes to Unleash. The headers are:
- `x-unleash-appname`: the name of the application that is using the client
- `x-unleash-connection-id`: a unique identifier for the current instance of the client
- `x-unleash-sdk`: sdk information in the format `unleash-js@<version>`
What should we call the client here? Is `unleash-js` correct? Should it be `unleash-browser`? `unleash-proxy-client`?
Second: should the client be possible to override? This package is also what powers our React, Svelte, and Vue SDKs. Should they be able to override it (so you'd get `unleash-react@<version>`)? I think that would be useful

feat(1 3223): add client identification headers

---

.github/workflows/release.yml

This commit re-pins the workflow version for the release template
reference.

meta: pin workflow version again

---

.gitignore
package.json
rollup.config.mjs
src/index.test.ts
src/index.ts
src/metrics.ts
src/version.ts
yarn.lock

Removes requiring version at runtime with require: https://github.com/Unleash/unleash-proxy-client-js/commit/3615f15dd4e297f0f82ea17eeec6f9791cf16f67#diff-258035e5968f6bf645400d417f310218d7d9a9a10606a3c34e7f55db193f58f3R3
Instead we're using the rollup replace plugin to read the version at build time and replace `__VERSION__` placeholder with the actual version number.
As a result other packages depending on this one don't need to understand require calls and also we're not exposing the whole package.json file at runtime.
To verify my claim above you can build the package and check the build directory after this change vs before this change.

fix: embed version at compile time

---

src/index.ts
src/uuidv4.ts

The one from the uuid library relies on an underlying crypto library
which doesn't exist at least in certain GitHub runners and may also
cause issues for react native applications.
This impl sidesteps that issue.
The same uuid generation method that we're cutting out here is also being used in `src/events-handler.ts`. However, because we haven't received any complaints about that, I'll leave it in.

chore(1-3230): use homebrew version of uuid generation

---

src/index.test.ts
src/index.ts

Retrieve stored into a temporary variable, instead of overriding it for the duration of a next promise. Avoid race conditions.
Before this change calls to `isEnabled` or `getVariant` could be resolved between stored toggles (empty list) are resolved and bootstrapped toggles are restored. This was causing https://github.com/Unleash/unleash-client-nextjs/issues/106

fix: unstable async bootstrap initialization

---

src/metrics.ts

When using unleash-proxy-client on the server side (e.g., for SSR or per-request flag fetching), we observed increasing memory usage and event loop handles even though .stop() was called immediately after .start().
After investigation, the issue was resolved by setting disableMetrics: true, suggesting that .stop () does not properly clean up background metrics collection.
Closes #245

fix(metrics): use clearInterval instead of clearTimeout in stop()

---

src/index.ts

Previously, the code attempted to abort controllers without checking their state, potentially causing issues. This change ensures that controllers are only aborted if they are not already in an aborted state, improving robustness and preventing unnecessary operations.
Closes #

Handle already aborted controllers before re-aborting

---

src/index.test.ts
src/index.ts

Closes #263 | https://github.com/Unleash/unleash/issues/10620
src/index.ts
This pull request improves error event handling in the `UnleashClient` class to provide more context about where errors originate. Now, when an error is emitted, it includes a `type` field indicating the source of the error, making it easier to debug and handle errors appropriately.
**Enhanced error event payloads:**
* Updated the `onError` handler in the `Metrics` instantiation to emit errors with a payload containing the error type (`'metrics'`) and the error object, instead of just the error.
* Modified error emission during toggle fetching to include the error type (`'fetch-toggles'`) and the error object, instead of just the error.

feat: improve error handling in metrics and fetch toggles
